#!/usr/bin/env python

import sys
import fileinput

# Read in each ref that the user is trying to update
for line in fileinput.input():
    print "post-receive: Trying to push ref: %s" % line

# Abort the push
# sys.exit(1)
