#!/bin/bash
curl https://api.github.com/repos/jimzucker/hygieia/events\?per_page\=100 2>/dev/null|python -c 'import sys, json;
print "sha".ljust(7," "),"type".ljust(10," "),"repo".ljust(10," "),"branch".ljust(10," "),"login".ljust(10," "),"message".ljust(40," ")
rows=json.load(sys.stdin);
for r in rows: 
	type = r["type"][0:10]	
	repo = r["repo"]["name"].split("/")[1][0:10]
	login = r["actor"]["login"][0:10]
	payload = r["payload"]
	sha = payload.get("head")[0:7]
	branch = payload["ref"].split("/")[2]
	print sha, type.ljust(10," "), repo.ljust(10," "), branch.ljust(10," "), login.ljust(10," "),"".ljust(40," ")

	for c in r["payload"]["commits"]:
		shaCommit = c["sha"][0:7]
		message = c["message"][0:40]
		print "".ljust(7," "),shaCommit[0:7].ljust(10," "),"".ljust(10,"."),"".ljust(10,"."), "".ljust(10,"."),message.ljust(40," ")
'

